"""Generated by Tresto v0.1.0

Test name: Login Test
Test description: Test user login functionality
Created Date: 2025-08-18

## Project Structure Overview
- src/components/ - React components including LoginForm, SignupForm
- src/services/ - API services for authentication and user management
- src/utils/ - Utility functions for validation and formatting

## Relevant Files for Test Case
- src/components/LoginForm.tsx - Main login component with email/password inputs
- src/services/auth.js - Authentication API calls and token management
- src/utils/validation.js - Form validation logic for login forms

## Key Components Found
- LoginForm component handles user authentication with form validation
- AuthService manages login/logout operations and token storage
- Validation utilities provide email and password validation"""

import pytest
from playwright.async_api import expect

async def test_login(page):
    await page.goto("https://example.com/login")
    await page.fill("#email", "test@example.com")
    await page.fill("#password", "password123")
    await page.click("button[type='submit']")
    await expect(page).to_have_url("**/dashboard")