from __future__ import annotations

from pathlib import Path

import pytest

from tresto.core.config.main import AIConfig, BrowserConfig, ProjectConfig, RecordingConfig, TrestoConfig
from tresto.core.scaffold import (
    CodebaseSnapshotBuilder,
    DatabaseCleanupRecommendation,
    ExistingScaffoldError,
    PlannedTest,
    ScaffoldPlan,
    ScaffoldWriter,
)


def _config(tmp_path: Path) -> TrestoConfig:
    return TrestoConfig(
        project=ProjectConfig(name="demo", url="http://localhost:3000", test_directory=tmp_path / "tresto" / "tests"),
        ai=AIConfig(connector="test", model="test-model"),
        browser=BrowserConfig.default(),
        recording=RecordingConfig.default(),
    )


def _plan(beneficial: bool = False) -> ScaffoldPlan:
    return ScaffoldPlan(
        project_overview="A demo web application.",
        detected_stack=["React", "Playwright"],
        conventions=["Components live in src/components"],
        planned_tests=[
            PlannedTest(
                test_name="auth.login",
                title="Login succeeds",
                description="Verify a user can log in with valid credentials.",
                priority="high",
                todo_steps=["Open the login page", "Submit valid credentials", "Assert dashboard is visible"],
            )
        ],
        database_cleanup=DatabaseCleanupRecommendation(
            beneficial=beneficial,
            rationale="Tests create durable users.",
            detected_technology="PostgreSQL",
            proposed_approach="Truncate test tables before each test.",
        ),
        open_questions=["Which seed user should be used?"],
    )


def test_snapshot_builder_excludes_tresto_and_heavy_dirs(tmp_path: Path) -> None:
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "App.jsx").write_text("export function App() { return null }", encoding="utf-8")
    (tmp_path / "node_modules").mkdir()
    (tmp_path / "node_modules" / "ignored.js").write_text("ignored", encoding="utf-8")
    (tmp_path / "tresto" / "tests").mkdir(parents=True)
    (tmp_path / "tresto" / "tests" / "test_existing.py").write_text("ignored", encoding="utf-8")

    snapshot = CodebaseSnapshotBuilder(tmp_path, Path("tresto/tests")).build()

    assert "src/App.jsx" in snapshot.tree
    assert "node_modules" not in snapshot.tree
    assert "tresto/tests" not in snapshot.tree
    assert [path for path, _ in snapshot.files] == ["src/App.jsx"]


def test_scaffold_writer_creates_readme_and_placeholder_test(tmp_path: Path) -> None:
    config = _config(tmp_path)
    result = ScaffoldWriter(config=config, plan=_plan()).write(enable_db_cleanup=False)

    assert result.readme_path == tmp_path / "tresto" / "README.md"
    assert result.readme_path.exists()
    assert "Login succeeds" in result.readme_path.read_text(encoding="utf-8")

    test_file = tmp_path / "tresto" / "tests" / "auth" / "test_login.py"
    assert test_file in result.test_files
    content = test_file.read_text(encoding="utf-8")
    assert "Generated by Tresto scaffold" in content
    assert "Test name: auth.login" in content
    assert "@pytest.mark.skip" in content
    assert "TODO: Submit valid credentials" in content


def test_scaffold_writer_refuses_hand_written_conflict_even_with_force(tmp_path: Path) -> None:
    config = _config(tmp_path)
    readme = tmp_path / "tresto" / "README.md"
    readme.parent.mkdir(parents=True)
    readme.write_text("# Hand written", encoding="utf-8")

    with pytest.raises(ExistingScaffoldError, match="hand-written"):
        ScaffoldWriter(config=config, plan=_plan(), force=True).write(enable_db_cleanup=False)


def test_scaffold_writer_replaces_generated_files_only_with_force(tmp_path: Path) -> None:
    config = _config(tmp_path)
    ScaffoldWriter(config=config, plan=_plan()).write(enable_db_cleanup=False)

    with pytest.raises(ExistingScaffoldError, match="Use --force"):
        ScaffoldWriter(config=config, plan=_plan()).write(enable_db_cleanup=False)

    result = ScaffoldWriter(config=config, plan=_plan(), force=True).write(enable_db_cleanup=False)
    assert result.readme_path.exists()


def test_scaffold_writer_adds_db_cleanup_hook_when_enabled(tmp_path: Path) -> None:
    config = _config(tmp_path)
    ScaffoldWriter(config=config, plan=_plan(beneficial=True)).write(enable_db_cleanup=True)

    conftest = tmp_path / "tresto" / "tests" / "conftest.py"
    content = conftest.read_text(encoding="utf-8")
    assert "BEGIN TRESTO SCAFFOLD DB CLEANUP" in content
    assert "tresto_scaffold_clean_database" in content
    assert "TRESTO_ENABLE_DB_CLEANUP" in content
